variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - container
  - build
  - package
  - bundle

container-armv7hf:
  image: docker:stable
  stage: container
  services:
    - docker:dind
  before_script:
    - docker info
    - echo -n $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
  script:
    - docker build -t ${CI_REGISTRY}/${CI_PROJECT_PATH}/armv7hf:latest -f ci/Dockerfile.debian ci/
    - docker push ${CI_REGISTRY}/${CI_PROJECT_PATH}/armv7hf:latest
    - mkdir -p artifacts
    - docker run --rm
        ${CI_REGISTRY}/${CI_PROJECT_PATH}/armv7hf:latest
        tar -C /opt -cJf - arm-buildroot-linux-gnueabihf_sdk-buildroot |
            cat > toolchain.tar.xz
  artifacts:
    name: toolchain-$CI_COMMIT_REF_NAME
    paths:
      - toolchain.tar.xz
  tags:
    - docker
  only:
    refs:
      - master
      - /^ci([-/].*)?$/
    changes:
      - .gitlab-ci.yml
      - .ci/Dockerfile.*
      - .ci/buildroot.config

build-native:
  image: fedora:31
  stage: build
  before_script:
    - dnf upgrade -y
    - dnf install -y meson ninja-build gcc
  script:
    - meson setup build
    - ninja -C build

build-armv7hf:
  image: ${CI_REGISTRY}/${CI_PROJECT_PATH}/armv7hf:latest
  stage: build
  script:
    - meson setup
        --prefix=/usr
        --cross-file /opt/arm-buildroot-linux-gnueabihf_sdk-buildroot/etc/meson/cross-compilation.conf
        build
    - ninja -C build
    - DESTDIR=inst ninja -C build install
  artifacts:
    paths:
      - build/inst

pkg-sc2:
  image: ${CI_REGISTRY}/${CI_PROJECT_PATH}/armv7hf:latest
  stage: package
  variables:
    GIT_STRATEGY: none
  dependencies:
    - build-armv7hf
  script:
    - tar -C build/inst -cpzf dema-rc.tar.gz .
  artifacts:
    name: dema-rc-$CI_COMMIT_REF_NAME
    paths:
      - dema-rc.tar.gz

pkg-sc2-deps:
  image: ${CI_REGISTRY}/${CI_PROJECT_PATH}/armv7hf:latest
  stage: package
  dependencies:
    - build-armv7hf
  script:
    - ./tools/bundler.sh
          -x 'ld-*.so' -x libc.so
          -q qemu-arm-static
          -o deps.tar
          /opt/arm-buildroot-linux-gnueabihf_sdk-buildroot
          arm-buildroot-linux-gnueabihf
          build/inst/usr/bin/dema-rc
    - gzip deps.tar
  artifacts:
    name: dema-rc-deps-$CI_COMMIT_REF_NAME
    paths:
      - deps.tar.gz

bundle-sc2:
  image: ${CI_REGISTRY}/${CI_PROJECT_PATH}/armv7hf:latest
  stage: bundle
  dependencies:
    - build-armv7hf
    - pkg-sc2
    - pkg-sc2-deps
  script:
    - mkdir -p build/bundle
    - tar -C build/bundle -xf dema-rc.tar.gz
    - tar -C build/bundle -xf deps.tar.gz
    - cp -a distro/sc2/. build/bundle
    - tar -C build/bundle -czf bundle.tar.gz .
  artifacts:
    name: dema-rc-bundle-$CI_COMMIT_REF_NAME
    paths:
      - bundle.tar.gz
