name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Update package cache
      run: sudo apt-get --assume-yes update
    - name: install dependencies
      run: |
        sudo apt-get install -y gcc ninja-build python3-pip python3-setuptools
        sudo -H pip3 install meson
    - name: configure
      run: meson setup build
    - name: build
      run: ninja -C build
