name: Docs

on:
  push:
    paths: 'docs/**'
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'

    - name: Update package cache
      run: sudo apt-get --assume-yes update
    - name: install dependencies
      run: |
        sudo apt-get install -y python3-pip python3-setuptools
        sudo -H pip3 install mkdocs mkdocs-material-extensions mkdocs-material mkdocs-material-components

    - name: Build docs
      run: mkdocs build

    - name: Deploy
      if: github.event_name != 'pull_request' && success()
      uses: crazy-max/ghaction-github-pages@v2
      with:
          target_branch: gh-pages
          build_dir: site
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
